**Задание 1**
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [8]:
import numpy as np
x = np.arange( 10, 0,-1 )
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [27]:
example_diag=np.diag(np.arange(10,-1,-1), k=0)
example_diag

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [29]:
a=sum(sum(example_diag))
a

55

**Задание 3**
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера.
 Определите какому фильму было выставлено больше всего оценок 5.0.

In [88]:
import pandas as pd
ratings = pd.read_csv('ratings.csv')
#ratings.head()
#ratings.info()
ratings.loc[ratings['rating']==5].groupby('movieId').count().sort_values('movieId', ascending=True).head()


userId  rating  timestamp
movieId                           
1            47      47         47
2             7       7          7
3             6       6          6
5             3       3          3
6            24      24         24

**Задание 4**
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года.
Не учитывайте в расчетах отрицательные значения quantity.

In [116]:
import pandas as pd
data = pd.read_csv('power.csv')
#data.head()
data=data[(data['year']>=2005) & (data['year']<=2010)&((data['country']=='Latvia')
|(data['country']=='Lithuania')|(data['country']=='Estonia'))
&((data['category']==4)|(data['category']==12)|(data['category']==12))&((data['quantity']>=0))]
data['quantity'].sum()

6372.0

**Задание 5**
Решите систему уравнений:
4x + 2y + z = 4 ;
x + 3y = 12;
5y + 4z = -3;

In [36]:
from numpy import linalg
a=np.array([[4,2,1],[1,3,0],[0,5,4]])
a
b=np.array([4,12,-3])
b
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])